### ISSUE TITLE
Add GET to samples & occurrences resources

### ISSUE THREAD

**Issue by kazlauskis** [Indicia-Team/drupal-7-module-iform_mobile_auth#10]
Allow fetching samples/occurrences without going after a specific report.

eg. **GET _/api/v1/samples?filter=personal&sort=asc_ HTTP/1.1**

```JSON
  "data": [{
    "type": "samples",
    "id": "1",
    "attributes": {
      ...
    },
   "type": "samples",
    "id": "2",
    "attributes": {
      ...
    }
```

**Comment by johnvanbreda** [comment]
Any work on the API should explore whether to enhance the rest_api module on the warehouse - see https://github.com/Indicia-Team/indicia-docs-rest-api.

**Comment by kazlauskis** [comment]
Yes, you are right. As we have spoken about this some time ago, the module will partly act as a proxy to the warehouse - the non-drupal resources should be accessed on the warehouse through the module.
