### ISSUE TITLE
Can you tell more about it?

### ISSUE THREAD

**Issue by ugintl** [Indicia-Team/drupal-7-module-iform_mobile_auth#15]
Looks interesting. Can you tell me more about this module? How to use it?

**Comment by JimBacon** [comment]
You'd be better looking at https://github.com/Indicia-Team/drupal-7-module-indicia-api which supersedes this module. It is part of the Indicia biological recording system and only relevant to you if you are a developer of mobile apps for Indicia. See http://indicia-docs.readthedocs.io/en/latest/contents.html for more information about Indicia.
