### ISSUE TITLE
Basic authentication

### ISSUE THREAD

**Issue by kazlauskis** [Indicia-Team/drupal-7-module-iform_mobile_auth#9]
Use [HTTP basic auth](https://en.wikipedia.org/wiki/Basic_access_authentication) and authenticate with every request using user password and not a generated secret (not sure if it is gives anything much), hopefully, we should move towards OAuth sometime soon.

**Comment by johnvanbreda** [comment]
oAuth was considered for Indicia's REST Api when designing it in collaboration with BTO and BSBI, but we opted for a simpler approach described at http://indicia-online-recording-rest-api.readthedocs.io/en/latest/authentication.html.

**Comment by kazlauskis** [comment]
OK, I think this requirement could then be just between the website (ie iRecord) and its client (ie an app). Our apps should support OAuth I've read somewhere that isn't very hard with DP8, not sure about DP7.

**Comment by BirenRathod** [comment]
It is not hard to use either of it. Both (7 & 8) requires to install and enable on the site.
here is the link https://www.drupal.org/project/oauth

**Comment by kazlauskis** [comment]
Thanks, @BirenRathod are there any plans to implement it on iRecord?

**Comment by johnvanbreda** [comment]
Some information that came from BTO which led to us not using oAuth at the time:
"3. Regarding oAuth. Some time ago Karen found some very damning blogs about oAuth (http://hueniverse.com/2012/07/26/oauth-2-0-and-the-road-to-hell/), and I also found some discussion (http://security.stackexchange.com/questions/52705/is-oauth-always-the-right-choice-and-when-isnt-it). I am not well enough versed in it to swing either way. I agree totally that we shouldn't create our own though, but need some discussion on a suitably lightweight, easy to implement at both ends, method." Having reviewed the information I could find at the time I agreed that oAuth 2 seemed to be more complex to learn and write a client against than necessary - oAuth 1 was simpler but we of course don't want to adopt an old standard. 

Note that simply turning on the Drupal oAuth module does not mean that it would then automatically work with our module - there would be some effort required to implement it from the mobile auth module.
